source 'https://rubygems.org'

gem 'sinatra'
gem 'thin'

gem 'opal', :git => 'https://github.com/opal/opal.git', :branch => 'master'
gem 'opal-jquery'
gem 'opal-vienna'
gem 'sass'

gem 'rspotify', :git => 'https://github.com/bebac/rspotify.git', :ref => '56a16924f556a16bb0c4b327641035be1c8064dd'
